name: Tests

on: [push, pull_request]

jobs:
  code-quality:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - run: make check-code-quality

  tests:
    needs: code-quality
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: snok/install-poetry@v1

      - name: Install project
        run: poetry install --no-interaction

      - run: make tests

  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JRubics/poetry-publish@v1.12
        if: startsWith(github.ref, 'refs/tags')
        with:
          python_version: "3.10"
          ignore_dev_requirements: true
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
